# FILE: roles/prep-rootfs/tasks/enable_services.yml
---
# Enable minimal services in the rootfs.

- name: Ensure systemd target wants directory exists
  ansible.builtin.file:
    path: "{{ staging_rootfs }}/etc/systemd/system/multi-user.target.wants"
    state: directory
    mode: "0755"

# If using ifupdown, ensure networking service is enabled.
- name: Enable networking service (if present)
  ansible.builtin.file:
    src: "/lib/systemd/system/networking.service"
    dest: "{{ staging_rootfs }}/etc/systemd/system/multi-user.target.wants/networking.service"
    state: link
    force: true
  ignore_errors: true

# Optional: enable SSH if later installed into rootfs
- name: Enable ssh service symlink if available
  ansible.builtin.file:
    src: "/lib/systemd/system/ssh.service"
    dest: "{{ staging_rootfs }}/etc/systemd/system/multi-user.target.wants/ssh.service"
    state: link
    force: true
  ignore_errors: true
