# FILE: roles/prep-rootfs/tasks/install_node_overrides.yml
---
# Add per-node writable NFS mounts and first-boot logic to the rootfs.

- name: Write /etc/systemd/system/state.mount
  ansible.builtin.copy:
    dest: "{{ staging_rootfs }}/etc/systemd/system/state.mount"
    mode: "0644"
    content: |
      [Unit]
      Description=Per-node state NFS mount
      [Mount]
      What={{ NFS_SERVER_IP }}:{{ NFS_EXPORT_PATH }}/nodes/%H/state
      Where=/state
      Type=nfs
      Options=_netdev
      [Install]
      WantedBy=multi-user.target

- name: Write /etc/systemd/system/var-lib-rancher-k3s.mount
  ansible.builtin.copy:
    dest: "{{ staging_rootfs }}/etc/systemd/system/var-lib-rancher-k3s.mount"
    mode: "0644"
    content: |
      [Unit]
      Description=Per-node k3s data mount
      [Mount]
      What={{ NFS_SERVER_IP }}:{{ NFS_EXPORT_PATH }}/nodes/%H/k3s
      Where=/var/lib/rancher/k3s
      Type=nfs
      Options=_netdev
      [Install]
      WantedBy=multi-user.target

- name: Write first-boot helper script
  ansible.builtin.copy:
    dest: "{{ staging_rootfs }}/usr/local/sbin/pi-firstboot.sh"
    mode: "0755"
    content: |
      #!/bin/sh
      set -eu
      for i in 1 2 3 4 5; do [ -d /state ] && break || sleep 1; done
      if [ -f /state/machine-id ]; then
        cp -f /state/machine-id /etc/machine-id
      else
        systemd-machine-id-setup >/dev/null 2>&1 || true
        mkdir -p /state
        cp -f /etc/machine-id /state/machine-id || true
      fi

- name: Write systemd unit for first-boot
  ansible.builtin.copy:
    dest: "{{ staging_rootfs }}/etc/systemd/system/pi-firstboot.service"
    mode: "0644"
    content: |
      [Unit]
      Description=Pi first boot setup
      After=network-online.target
      Wants=network-online.target
      [Service]
      Type=oneshot
      ExecStart=/usr/local/sbin/pi-firstboot.sh
      RemainAfterExit=yes
      [Install]
      WantedBy=multi-user.target

- name: Enable pi-firstboot.service
  ansible.builtin.file:
    src: "/etc/systemd/system/pi-firstboot.service"
    dest: "{{ staging_rootfs }}/etc/systemd/system/multi-user.target.wants/pi-firstboot.service"
    state: link
    force: true
