# FILE: roles/prep-rootfs/tasks/main.yml
---
# Build minimal Raspberry Pi OS rootfs for diskless nodes.

- name: Ensure staging directories are created
  import_tasks: ensure_directories.yml

- name: Install debootstrap utility on controller
  import_tasks: install_debootstrap.yml

- name: Create base Raspberry Pi OS root filesystem
  import_tasks: create_rootfs.yml

- name: Configure hostname inside rootfs
  import_tasks: configure_hostname.yml

- name: Configure fstab inside rootfs
  import_tasks: configure_fstab.yml

- name: Enable essential services in rootfs
  import_tasks: enable_services.yml

- name: Install systemd per-node NFS mounts and first-boot service
  import_tasks: install_node_overrides.yml

- name: Verify rootfs completeness
  import_tasks: verify_rootfs.yml
