# FILE: roles/prep-rootfs/tasks/verify_rootfs.yml
---
# Verify that the rootfs has the essential files.

- name: Check os-release
  ansible.builtin.stat:
    path: "{{ staging_rootfs }}/etc/os-release"
  register: _osrel

- name: Check hostname
  ansible.builtin.stat:
    path: "{{ staging_rootfs }}/etc/hostname"
  register: _host

- name: Check fstab
  ansible.builtin.stat:
    path: "{{ staging_rootfs }}/etc/fstab"
  register: _fstab

- name: Fail if required files are missing
  ansible.builtin.fail:
    msg: "Rootfs verification failed: missing one or more required files (/etc/os-release, /etc/hostname, /etc/fstab)."
  when: not (_osrel.stat.exists and _host.stat.exists and _fstab.stat.exists)
