- name: Install required packages (APT)
  ansible.builtin.apt:
    name:
      - curl
      - git
      - nfs-common
      - python3-pip
      - python3-kubernetes
    state: present
    update_cache: true
  become: true
