# FILE: roles/prep-kernel/tasks/build_kernel.yml
---
# No source build in Day-0; ensure the kernel modules are installed on host.

- name: Verify kernel modules directory exists
  ansible.builtin.shell: "ls -d /lib/modules/* 2>/dev/null | head -n1"
  register: _mods
  changed_when: false

- name: Warn if no modules directory found
  ansible.builtin.debug:
    msg: "Warning: /lib/modules not found; ensure host kernel packages are installed."
  when: _mods.stdout == ""
