# FILE: roles/prep-kernel/tasks/create_initramfs.yml
---
# Ensure an initramfs exists (we reuse the host's initramfs image).

- name: Check for initrd presence
  ansible.builtin.shell: ls -1 /boot/initrd.img-* 2>/dev/null | head -n1
  register: _initrd
  changed_when: false

- name: Fail if initrd is missing
  ansible.builtin.fail:
    msg: "No initrd found under /boot; install initramfs-tools and generate one."
  when: _initrd.stdout == ""
