# FILE: roles/prep-kernel/tasks/ensure_directories.yml
---
# Ensure all directories required for kernel build, staging, and publish exist.
# Use become + loop + exclude /run traversal to avoid permission issues.

- name: Ensure kernel build and publish directories exist
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    recurse: false   # Avoid recursing into /run/netns accidentally
  loop:
    - "{{ staging_dir }}"
    - "{{ staging_boot }}"
    - "{{ boot_publish_path }}"
