# FILE: roles/prep-kernel/tasks/fetch_kernel_sources.yml
---
# Day-0 design reuses the host's kernel; verify its presence.

- name: Find installed kernel image(s)
  ansible.builtin.shell: ls -1 /boot/vmlinuz-* 2>/dev/null | head -n1
  register: _vk
  changed_when: false

- name: Find installed initrd image(s)
  ansible.builtin.shell: ls -1 /boot/initrd.img-* 2>/dev/null | head -n1
  register: _ik
  changed_when: false

- name: Fail if kernel or initrd are not present on host
  ansible.builtin.fail:
    msg: "Host kernel/initrd not found in /boot; install {{ kernel_pkg }} and initramfs-tools."
  when: _vk.stdout == "" or _ik.stdout == ""
