# FILE: roles/prep-kernel/tasks/install_build_tools.yml
---
# Install required tools on the build host.

- name: Install kernel build and initramfs tools
  ansible.builtin.apt:
    name:
      - "{{ kernel_pkg }}"
      - "{{ initramfs_pkg }}"
      - rsync
      - cpio
      - kmod
      - gzip
    state: present
    update_cache: true
  become: true
