# FILE: roles/prep-kernel/tasks/main.yml
---
# Build and stage Raspberry Pi 5 kernel, initramfs, and boot files.

- name: Ensure staging directories are created
  import_tasks: ensure_directories.yml

- name: Install base build tools
  import_tasks: install_build_tools.yml

- name: Fetch or install kernel sources
  import_tasks: fetch_kernel_sources.yml

- name: Build kernel and supporting modules
  import_tasks: build_kernel.yml

- name: Create initramfs image
  import_tasks: create_initramfs.yml

- name: Prepare kernel and initramfs for NFS netboot
  import_tasks: prepare_kernel_initrd.yml

- name: Verify kernel and initrd artifacts
  import_tasks: verify_artifacts.yml
