# FILE: roles/prep-kernel/tasks/verify_artifacts.yml
---
# Verify that the published HTTP boot artifacts exist.

- name: Check published kernel
  ansible.builtin.stat:
    path: "{{ boot_publish_path }}/{{ kernel_filename }}"
  register: _vkpub

- name: Check published initrd
  ansible.builtin.stat:
    path: "{{ boot_publish_path }}/{{ initrd_filename }}"
  register: _ikpub

- name: Check published iPXE script
  ansible.builtin.stat:
    path: "{{ boot_publish_path }}/{{ ipxe_filename }}"
  register: _ipxepub

- name: Fail if published artifacts are missing
  ansible.builtin.fail:
    msg: "HTTP boot artifacts missing (kernel/initrd/ipxe) in {{ boot_publish_path }}"
  when: not (_vkpub.stat.exists and _ikpub.stat.exists and _ipxepub.stat.exists)
